---
- hosts: localhost
  vars:
    rancher_name: rancher_server
    rancher_port: 8080
    rancher_version: v1.1.4
    rancher_db_host: dbhost.xxx
    rancher_db_name: dbname
    rancher_db_user: dbuser
    rancher_db_pass: dbpass
    rancher_db_port: 3306

  tasks:

  - name: Gather facts
    action: ec2_facts

  - name: setup disk alarm
    ec2_metric_alarm:
      state: present
      region: "{{ ansible_ec2_placement_region }}"
      name: "disk-alarm-{{ ansible_ec2_instance_id }}"
      metric: "DiskSpaceUtilization"
      namespace: "System/Linux"
      statistic: Average
      comparison: ">="
      threshold: "90.0"
      period: 300
      evaluation_periods: 3
      unit: "Percent"
      description: "When disk usage is greater than 80% for instance {{ ansible_ec2_instance_id }}"
      dimensions: {'Filesystem':'/dev/xvda1','InstanceId':'{{ ansible_ec2_instance_id }}','MountPath':'/'}
      alarm_actions: ["{{ sns_alarm_action }}"]
    environment:
      EC2_SECRET_KEY: "{{ cloudwatch_aws_secret_key }}"
      EC2_ACCESS_KEY: "{{ cloudwatch_aws_access_key_id }}"
      AWS_REGION: "{{ ansible_ec2_placement_region }}"

  - name: setup memory alarm
    ec2_metric_alarm:
      state: present
      region: "{{ ansible_ec2_placement_region }}"
      name: "memory-alarm-{{ ansible_ec2_instance_id }}"
      metric: "MemoryUtilization"
      namespace: "System/Linux"
      statistic: Average
      comparison: ">="
      threshold: "95.0"
      period: 300
      evaluation_periods: 3
      unit: "Percent"
      description: "When memory usage is greater than 95% for instance {{ ansible_ec2_instance_id }}"
      dimensions: {'InstanceId':'{{ ansible_ec2_instance_id }}'}
      alarm_actions: ["{{ sns_alarm_action }}"]
    environment:
      EC2_SECRET_KEY: "{{ cloudwatch_aws_secret_key }}"
      EC2_ACCESS_KEY: "{{ cloudwatch_aws_access_key_id }}"
      AWS_REGION: "{{ ansible_ec2_placement_region }}"
  
  - name: setup cpu alarm
    ec2_metric_alarm:
      state: present
      region: "{{ ansible_ec2_placement_region }}"
      name: "cpu-alarm-{{ ansible_ec2_instance_id }}"
      metric: "CPUUtilization"
      namespace: "AWS/EC2"
      statistic: Average
      comparison: ">="
      threshold: "95.0"
      period: 300
      evaluation_periods: 3
      unit: "Percent"
      description: "When cpu usage is greater than 95% for instance {{ ansible_ec2_instance_id }}"
      dimensions: {'InstanceId':'{{ ansible_ec2_instance_id }}'}
      alarm_actions: ["{{ sns_alarm_action }}"]
    environment:
      EC2_SECRET_KEY: "{{ cloudwatch_aws_secret_key }}"
      EC2_ACCESS_KEY: "{{ cloudwatch_aws_access_key_id }}"
      AWS_REGION: "{{ ansible_ec2_placement_region }}"

  - name: Pull and run the Rancher/server container
    docker:
      name: "{{ rancher_name }}"
      image: rancher/server:{{ rancher_version }}
      restart_policy: always
      ports:
        - "{{ rancher_port }}:8080"
      env:
        CATTLE_DB_CATTLE_MYSQL_HOST: "{{ rancher_db_host }}"
        CATTLE_DB_CATTLE_MYSQL_PORT: "{{ rancher_db_port }}"
        CATTLE_DB_CATTLE_MYSQL_NAME: "{{ rancher_db_name }}"
        CATTLE_DB_CATTLE_USERNAME: "{{ rancher_db_user }}"
        CATTLE_DB_CATTLE_PASSWORD: "{{ rancher_db_pass }}"
